version: '3'

services:

  api-service1:
    image: api-service1:latest
    container_name: api-service1
    hostname: api-service1
    build:
      context: ./api-service1
    ports:
      - 5001:5000

  api-service2:
    image: api-service2:latest
    container_name: api-service2
    hostname: api-service2
    build:
      context: ./api-service2
    ports:
      - 5002:5000

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    hostname: api-gateway
    build:
      context: ./nginx
    ports:
      - 80:80
